export default [
	{
		slug: "toggle-switch",
		title: "Toggle Switch",
		description: "A styled on/off toggle built with a checkbox and CSS.",
		tags: ["forms", "interactive"],
		category: "form",
		categoryLabel: "Form",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "floating-labels",
		title: "Floating Labels",
		description: "Form labels that float above the input on focus using `:placeholder-shown`.",
		tags: ["forms"],
		category: "form",
		categoryLabel: "Form",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "star-rating",
		title: "Star Rating",
		description: "Clickable star rating using radio inputs and the general sibling combinator.",
		tags: ["forms", "interactive"],
		category: "form",
		categoryLabel: "Form",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "expandable-search",
		title: "Expandable Search",
		description: "A search bar that expands on focus with a smooth CSS transition.",
		tags: ["forms", "layout"],
		category: "nav",
		categoryLabel: "Navigation",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "show-hide-content",
		title: "Show / Hide Content",
		description: "Toggle visibility of content using a checkbox and the ~ combinator.",
		tags: ["interactive", "layout"],
		category: "layout",
		categoryLabel: "Layout",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "dark-light-mode",
		title: "Dark / Light Mode",
		description: "A theme switcher using a checkbox, CSS custom properties, and no JS.",
		tags: ["interactive", "theming"],
		category: "feedback",
		categoryLabel: "Feedback",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "accordion",
		title: "Accordion / FAQ",
		description: "Expandable content panels using the `&lt;details&gt;` and `&lt;summary&gt;` elements.",
		tags: ["interactive", "layout"],
		category: "layout",
		categoryLabel: "Layout",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "tab-navigation",
		title: "Tab Navigation",
		description: "Tabbed interface using radio inputs and the `:checked` pseudo-class.",
		tags: ["interactive", "navigation"],
		category: "nav",
		categoryLabel: "Navigation",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "hover-tooltip",
		title: "Hover Tooltip",
		description: "Tooltips on hover using CSS pseudo-elements and the `data-tip` attribute.",
		tags: ["interactive"],
		category: "feedback",
		categoryLabel: "Feedback",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "custom-checkboxes",
		title: "Custom Checkboxes",
		description: "Fully styled checkboxes using `appearance:none` and `:checked`.",
		tags: ["forms"],
		category: "form",
		categoryLabel: "Form",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "custom-radio",
		title: "Custom Radio Buttons",
		description: "Styled radio buttons without any images or JavaScript.",
		tags: ["forms"],
		category: "form",
		categoryLabel: "Form",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "range-slider",
		title: "Styled Range Slider",
		description: "A custom-styled range input using CSS track and thumb pseudo-elements.",
		tags: ["forms"],
		category: "form",
		categoryLabel: "Form",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "progress-bar",
		title: "Progress Bars",
		description: "Animated progress bars using the `&lt;progress&gt;` element and CSS.",
		tags: ["visual"],
		category: "feedback",
		categoryLabel: "Feedback",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "click-reveal",
		title: "Click-to-Reveal",
		description: "Content that reveals on click using a checkbox as state.",
		tags: ["interactive"],
		category: "layout",
		categoryLabel: "Layout",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "card-flip",
		title: "3D Card Flip",
		description: "A card that flips on hover using CSS 3D transforms and perspective.",
		tags: ["visual", "interactive"],
		category: "layout",
		categoryLabel: "Layout",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "image-zoom",
		title: "Image Zoom on Hover",
		description: "Smooth image zoom on hover using CSS transform and `overflow:hidden`.",
		tags: ["visual", "interactive"],
		category: "layout",
		categoryLabel: "Layout",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "gradient-text",
		title: "Gradient Text",
		description: "Text filled with a gradient using `background-clip:text`.",
		tags: ["visual"],
		category: "layout",
		categoryLabel: "Layout",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "skeleton-loader",
		title: "Skeleton Loader",
		description: "Animated placeholder loading state using CSS keyframes.",
		tags: ["visual"],
		category: "feedback",
		categoryLabel: "Feedback",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "hover-dropdown",
		title: "Hover Dropdown Menu",
		description: "A navigation dropdown that opens on hover using `:hover` and `visibility`.",
		tags: ["navigation", "interactive"],
		category: "nav",
		categoryLabel: "Navigation",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "modal-dialog",
		title: "Modal Dialog",
		description: "A modal using `:target` to show/hide without JavaScript.",
		tags: ["interactive", "layout"],
		category: "layout",
		categoryLabel: "Layout",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "offcanvas-nav",
		title: "Off-Canvas Navigation",
		description: "A slide-in navigation panel using a checkbox and CSS translate.",
		tags: ["navigation", "interactive"],
		category: "nav",
		categoryLabel: "Navigation",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "input-validation",
		title: "CSS Input Validation",
		description: "Real-time form validation feedback using `:valid`, `:invalid`, and `:user-invalid`.",
		tags: ["forms"],
		category: "form",
		categoryLabel: "Form",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
	{
		slug: "number-counter",
		title: "Animated Number Counter",
		description: "Numbers that count up using `@property`, CSS counters, and animations.",
		tags: ["visual"],
		category: "feedback",
		categoryLabel: "Feedback",
		level: "advanced",
		levelLabel: "Advanced",
	},
	{
		slug: "scroll-carousel",
		title: "Scroll Snap Carousel",
		description: "A horizontal carousel using `scroll-snap-type` and `scroll-snap-align`.",
		tags: ["layout", "interactive"],
		category: "layout",
		categoryLabel: "Layout",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "aspect-ratio-box",
		title: "Aspect Ratio Box",
		description: "Maintain a fixed aspect ratio on any element using the `aspect-ratio` property.",
		tags: ["layout"],
		category: "layout",
		categoryLabel: "Layout",
		level: "beginner",
		levelLabel: "Beginner",
	},
	{
		slug: "scroll-spy",
		title: "Scroll Spy Indicator",
		description: "A reading progress bar that tracks scroll position using CSS scroll-driven animations.",
		tags: ["visual", "layout"],
		category: "nav",
		categoryLabel: "Navigation",
		level: "advanced",
		levelLabel: "Advanced",
	},
	{
		slug: "glitch-effect",
		title: "Glitch Effect",
		description: "An animated text glitch using `clip-path`, pseudo-elements, and CSS keyframes — no JavaScript.",
		tags: ["visual"],
		category: "layout",
		categoryLabel: "Layout",
		level: "intermediate",
		levelLabel: "Intermediate",
	},
];
